### ISSUE TITLE
Flowise Error: Expected content-type to be text/event-stream, Actual: application/json; charset=utf-8

### ISSUE THREAD

**Issue by j-d-carmichael** [FlowiseAI/FlowiseChatEmbed#249]
flowise: latest
embed code: suggested from flowise

I am having the exact same issue as https://stackoverflow.com/questions/79005072/flowise-error-expected-content-type-to-be-text-event-stream-actual-applicatio

- We have flowise protected behind and nginx proxy.
- Everything works fine except the embedded chatbots don't fully function... they load just fine, but it sends a request to know if it should stream or not.. it returns `streaming: true`.
- When sending the question to the server, streaming: true is sent in the payload but the response from the server, is application/json

This results in the embedded js code saying:
`Flowise Error: Expected content-type to be text/event-stream, Actual: application/json; charset=utf-8` 

The same agent works fine within the "designer canvas", but we also note that in the flowise designer a socket connection is established  where as with the embed code there is no socket established.

Any ideas?

**Comment by Nadiahadjmbarek** [comment]
same issue

**Comment by nikitas-novatix** [comment]
I have exactly the same issue, please work fast on this

**Comment by Panconjugo23** [comment]
Hey guys, I am the one who created the stackoverflow above. After researching for some hours I found out that the latest versions 2.0.1 and 2.0.0 are the ones not working, so in case your are copying and pasting the embedding script add the version 1.3.14

[](import Chatbot from "https://cdn.jsdelivr.net/npm/flowise-embed@1.3.14/dist/web.js")

I didn't research further to understand why the latest versions are not working so in case someone knows the real issue please share it.

**Comment by blissiraDC** [comment]
So its to do with the new SSE streaming not working with this new FlowiseEmbed version? Was hoping the day had come where we could finally see responses streamed!

**Comment by croftie** [comment]
Same here

**Comment by mkmatzat** [comment]
Same problem here. The tip from @Panconjugo23 helped, many thanks! 
I will put the working web.js on my own server to avoid surprises in future.

**Comment by xbiggyl** [comment]
This is still not fixed. 
I'm having the same problem on a wordpress website + nginx 

Manually adding the version number as @Panconjugo23 mentioned is still the only solution.

**Comment by ShaneMuir** [comment]
Same here version 2.0.6 no likely

**Comment by ShaneMuir** [comment]
> Same here version 2.0.6 no likely
> 
> ```
> web.js:1 EventSource Error:  Error
>     at onopen (web.js:1:931822)
>     at A (web.js:1:923895)
>     ```
> ```

UPDATE - I was running an old version of flowise on the backend so updating that has resolved my issue. 

https://github.com/FlowiseAI/Flowise
